/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetotrabalhofuncoes;

import javax.swing.JOptionPane;

/**
 *
 * @author francisco.eslima1
 */
public class JrmProjeto1 extends javax.swing.JFrame {

    

    /**
     * Creates new form JrmProjeto1
     */
    public JrmProjeto1() {
        
        initComponents();
 
        //Centralizar a tela
        setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        rbPow = new javax.swing.JRadioButton();
        rbSqrt = new javax.swing.JRadioButton();
        rbRandom = new javax.swing.JRadioButton();
        rbFloor = new javax.swing.JRadioButton();
        rbMax = new javax.swing.JRadioButton();
        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        lblResultado = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        txtC = new javax.swing.JTextField();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("               Funções");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup1.add(rbPow);
        rbPow.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbPow.setText("Elevar Um Número Ao Quadrado");
        rbPow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPowActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbSqrt);
        rbSqrt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbSqrt.setText("Raiz Quadrada De Um Número");
        rbSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSqrtActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbRandom);
        rbRandom.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbRandom.setText("Número Aleatório de (0 - 20)");
        rbRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRandomActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbFloor);
        rbFloor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbFloor.setText("Arredondar Um Número ");
        rbFloor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFloorActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbMax);
        rbMax.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbMax.setText("Valor Mais Alto Entre 3 Números");
        rbMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMaxActionPerformed(evt);
            }
        });

        txtA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAActionPerformed(evt);
            }
        });

        txtB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBActionPerformed(evt);
            }
        });

        lblResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblResultadoActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        txtC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rbMax)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lblResultado))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rbSqrt)
                    .addComponent(rbPow)
                    .addComponent(rbRandom)
                    .addComponent(rbFloor))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(rbSqrt)
                .addGap(18, 18, 18)
                .addComponent(rbPow)
                .addGap(18, 18, 18)
                .addComponent(rbRandom)
                .addGap(18, 18, 18)
                .addComponent(rbFloor)
                .addGap(18, 18, 18)
                .addComponent(rbMax)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Operacoes op = new Operacoes();

    private void rbPowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPowActionPerformed

        try {
            double a = Double.parseDouble(txtA.getText());

            lblResultado.setText(String.format("%.2f", op.pow(a)));
        } catch (NumberFormatException stringVazia) {

            JOptionPane.showMessageDialog(null, "Campos Vazios! \n ERRO: " + stringVazia.toString(), "ERRO!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_rbPowActionPerformed

    private void rbSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSqrtActionPerformed

        try {

            double a = Double.parseDouble(txtA.getText());

            if (a < 0) {

                lblResultado.setText("Nan");
            } else {

                lblResultado.setText(String.format("%.2f", op.sqrt(a)));
            }

        } catch (NumberFormatException stringVazia) {

            JOptionPane.showMessageDialog(null, "Campos Vazios! \n ERRO: " + stringVazia.toString(), "ERRO!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_rbSqrtActionPerformed

    private void rbRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRandomActionPerformed

        lblResultado.setText(String.format("%d", op.random(WIDTH)));
    }//GEN-LAST:event_rbRandomActionPerformed

    private void rbFloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFloorActionPerformed

        try {
            double a = Double.parseDouble(txtA.getText());

            lblResultado.setText(String.format("%.2f", op.arred(a)));
        } catch (NumberFormatException stringVazia) {

            JOptionPane.showMessageDialog(null, "Campos Vazios! \n ERRO: " + stringVazia.toString(), "ERRO!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_rbFloorActionPerformed

    private void rbMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMaxActionPerformed

        try {
            double a = Double.parseDouble(txtA.getText());
            double b = Double.parseDouble(txtB.getText());
            double c = Double.parseDouble(txtC.getText());

            lblResultado.setText(String.format("%.2f", op.max(a, b, c)));
        } catch (NumberFormatException stringVazia) {

            JOptionPane.showMessageDialog(null, "Campos Vazios! \n ERRO: " + stringVazia.toString(), "ERRO!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_rbMaxActionPerformed

    private void txtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

        lblResultado.setText("");
        txtA.setText("");
        txtB.setText("");
        txtC.setText("");
        txtA.requestFocus();
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBActionPerformed

    private void lblResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblResultadoActionPerformed

    private void txtCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JrmProjeto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JrmProjeto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JrmProjeto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JrmProjeto1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JrmProjeto1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField lblResultado;
    private javax.swing.JRadioButton rbFloor;
    private javax.swing.JRadioButton rbMax;
    private javax.swing.JRadioButton rbPow;
    private javax.swing.JRadioButton rbRandom;
    private javax.swing.JRadioButton rbSqrt;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtC;
    // End of variables declaration//GEN-END:variables
}
